import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';

export type Language = 'en' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  loading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.browse': 'Browse',
    'nav.golf': 'Golf',
    'nav.tennis': 'Tennis',
    'nav.padel': 'Padel',
    'nav.hockey': 'Hockey',
    'nav.cycling': 'Cycling',
    'nav.signin': 'Sign In',
    'nav.profile': 'Profile',
    'nav.orders': 'My Orders',
    'nav.list': 'List Item',
    'nav.signout': 'Sign Out',
    
    // Auth
    'auth.welcome': 'Welcome Back',
    'auth.subtitle': 'Sign in to continue your sustainable sports journey',
    'auth.tagline': 'RELIVE. RELOVE. RESPORTZ.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signin': 'Sign In',
    'auth.signing': 'Signing In...',
    'auth.noaccount': 'Don\'t have an account? Join Resportz',
    'auth.back': 'Back to Home',
    'auth.enter.email': 'Enter your email',
    'auth.enter.password': 'Enter your password',
    
    // Hero Section
    'hero.title': 'Resportz',
    'hero.tagline': 'RELIVE. RELOVE. RESPORTZ.',
    'hero.subtitle': 'The sustainable marketplace for sports equipment. Buy and sell quality gear from passionate athletes in your community.',
    'hero.cta': 'Get Started',
    'hero.browse': 'Browse Products',
    'hero.verified': 'Verified Quality',
    'hero.secure': 'Secure Payments',
    'hero.local': 'Local Community',
    'hero.quote': 'Find premium sports equipment from fellow athletes who know quality gear',
    'hero.quote.author': 'The Resportz Community',
    
    // Home/Landing
    'hero.cta.alt': 'Start Shopping',
    'hero.list': 'List Your Gear',
    'home.welcome': 'Welcome to Resportz!',
    'home.welcome.user': 'Welcome',
    'home.subtitle': 'Your sustainable sports marketplace is ready. Choose how you\'d like to get started.',
    'home.start.shopping': 'Start Shopping',
    'home.start.shopping.desc': 'Browse quality pre-owned sports equipment from fellow athletes. Find gear that performs at prices you\'ll love.',
    'home.start.selling': 'Start Selling',
    'home.start.selling.desc': 'Give your sports equipment a second life. List your gear and earn money while helping other athletes.',
    'home.list.gear': 'List Your Gear',
    'home.browse.products': 'Browse Products',
    'home.stats.athletes': 'Active Athletes',
    'home.stats.sold': 'Items Sold',
    'home.stats.satisfaction': 'Satisfaction Rate',
    'home.popular.categories': 'Popular Categories',
    'home.popular.desc': 'Discover quality equipment across all your favorite sports',
    'home.cta.title': 'Ready to Join the Movement?',
    'home.cta.subtitle': 'Sustainable sports equipment trading for athletes, by athletes',
    'home.why.title': 'Why Choose Resportz?',
    'home.why.subtitle': 'The smart, efficient way to buy and sell quality sports equipment. We make trading sports gear simple, secure, and community-driven.',
    'home.effortless.title': 'Effortless Trading',
    'home.effortless.desc': 'List your gear in minutes or find exactly what you need with our streamlined platform designed for busy athletes.',
    'home.quality.title': 'Quality Assured',
    'home.quality.desc': 'Every item is carefully vetted by our community of sports enthusiasts to ensure you get gear that performs.',
    'home.community.title': 'Community Driven',
    'home.community.desc': 'Connect with fellow athletes who share your passion for sports and understand the value of quality equipment.',
    
    // Browse
    'browse.title': 'Browse Products',
    'browse.subtitle': 'Discover quality used sports equipment from trusted sellers',
    'browse.search': 'Search products, brands...',
    'browse.all': 'All Products',
    'browse.items': 'items',
    'browse.continue': 'Continue Shopping',
    'browse.error': 'Error loading products',
    
    // Categories
    'category.golf': 'Golf',
    'category.golf.desc': 'Professional clubs, balls, and accessories for every golfer',
    'category.golf.detailed': 'Clubs, balls, apparel, and golf accessories',
    'category.tennis': 'Tennis',
    'category.tennis.desc': 'Rackets, shoes, and gear for court champions',
    'category.tennis.detailed': 'Rackets, balls, shoes, apparel, and court accessories',
    'category.padel': 'Padel',
    'category.padel.desc': 'Rackets and equipment for the fastest growing sport',
    'category.padel.detailed': 'Rackets, balls, shoes, apparel, and court equipment',
    'category.hockey': 'Hockey',
    'category.hockey.desc': 'Sticks, skates, and protective gear for ice warriors',
    'category.hockey.detailed': 'Sticks, pucks, protective gear, and hockey accessories',
    'category.cycling': 'Cycling',
    'category.cycling.desc': 'Bikes, helmets, and accessories for every ride',
    'category.cycling.detailed': 'Bikes, components, apparel, and cycling accessories',
    'category.equipment': 'Equipment',
    'category.browse': 'Browse',
    'category.from': 'equipment from trusted sellers',
    'category.shop.title': 'Shop by Sport',
    'category.shop.subtitle': 'Discover quality sports equipment across all your favorite sports',
    'category.browse.all.sports': 'Browse All Sports',
    
    // Product
    'product.condition': 'Condition',
    'product.size': 'Size',
    'product.description': 'Description',
    'product.add.cart': 'Add to Cart',
    'product.contact.seller': 'Contact Seller Directly',
    'product.not.available': 'Not Available',
    'product.own.product': 'This is your product',
    'product.save.amount': 'You save',
    'product.seller': 'By',
    'product.loading': 'Loading...',
    'product.error': 'Product not found',
    'product.related': 'Related Products',
    'product.shipping': 'Shipping & Returns',
    'product.shipping.desc': 'Free shipping on orders over €50. 30-day return policy.',
    
    // Featured Products
    'featured.title': 'Featured Products',
    'featured.view.all': 'View All',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.signin': 'Please sign in to view your cart',
    'cart.empty': 'Your cart is empty',
    'cart.empty.subtitle': 'Looks like you haven\'t added any items to your cart yet',
    'cart.start': 'Start Shopping',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.free': 'Free',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.quantity': 'Qty',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.signin': 'Please sign in to checkout',
    'checkout.shipping': 'Shipping Address',
    'checkout.payment': 'Payment Method',
    'checkout.summary': 'Order Summary',
    'checkout.fullname': 'Full Name',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.postal': 'Postal Code',
    'checkout.country': 'Country',
    'checkout.subtotal': 'Subtotal',
    'checkout.commission': 'ReSport commission (5%)',
    'checkout.pay': 'Pay with Stripe',
    'checkout.creating': 'Creating checkout...',
    'checkout.held': 'Payment held until delivery verification. Sellers receive 95% after completion.',
    'checkout.secure': 'Secure payment processing via Stripe. Payment will be held until delivery verification is complete.',
    
    // Success/Cancel
    'success.title': 'Payment Successful!',
    'success.thanks': 'Thank you for your purchase! Your payment has been received and is being held securely until delivery verification.',
    'success.reference': 'Order Reference',
    'success.details': '• Payment is held securely until delivery verification\n• Sellers will be notified of your order\n• You\'ll receive tracking information once shipped\n• Sellers receive payment after successful delivery',
    'success.orders': 'View Orders',
    'success.continue': 'Continue Shopping',
    'success.processing': 'Processing your order...',
    
    'cancel.title': 'Payment Cancelled',
    'cancel.message': 'Your payment was cancelled. No charges have been made to your account.',
    'cancel.cart': 'Your items are still in your cart and you can complete your purchase when you\'re ready.',
    'cancel.return': 'Return to Cart',

    // Signup
    'signup.title': 'Create Your Account',
    'signup.subtitle': 'Join the sustainable sports community',
    'signup.fullname': 'Full Name',
    'signup.fullname.placeholder': 'Enter your full name',
    'signup.password.placeholder': 'Create a password',
    'signup.create': 'Create Account',
    'signup.creating': 'Creating Account...',
    'signup.hasaccount': 'Already have an account? Sign in',
    'signup.name.required': 'Name required',
    'signup.name.required.desc': 'Please enter your full name.',
    'signup.email.required': 'Email required',
    'signup.email.required.desc': 'Please enter your email address.',
    'signup.password.required': 'Password required',
    'signup.password.required.desc': 'Please enter a password.',
    'signup.account.exists': 'Account exists',
    'signup.account.exists.desc': 'An account with this email already exists. Try signing in instead.',
    'signup.failed': 'Signup failed',
    'signup.success': 'Account created!',
    'signup.success.desc': 'Welcome to ReSport! Let\'s complete your profile.',
    'signup.error.general': 'Something went wrong. Please try again.',

    // Onboarding
    'onboarding.subtitle': 'Join the sustainable sports movement. Buy and sell quality used sports equipment for running, golf, football, and more.',
    'onboarding.buyer': 'I\'m a Buyer',
    'onboarding.buyer.desc': 'Discover quality pre-owned sports equipment at great prices. From running shoes to golf clubs, find gear that performs.',
    'onboarding.seller': 'I\'m a Seller',
    'onboarding.seller.desc': 'Give your sports equipment a second life. Earn money while helping other athletes find quality gear.',
    'onboarding.start.shopping': 'Start Shopping',
    'onboarding.signup.buy': 'Sign Up to Buy',
    'onboarding.start.selling': 'Start Selling',
    'onboarding.signup.sell': 'Sign Up to Sell',
    'onboarding.community': 'Community',
    'onboarding.community.desc': 'Connect with fellow athletes',
    'onboarding.quality': 'Quality',
    'onboarding.quality.desc': 'Vetted equipment you can trust',
    'onboarding.sustainable': 'Sustainable',
    'onboarding.sustainable.desc': 'Better for you and the planet',

    // Not Found
    'notfound.title': 'Page Not Found',
    'notfound.message': 'Sorry, we couldn\'t find the page you\'re looking for. Perhaps you\'ve mistyped the URL or the page has been moved.',
    'notfound.home': 'Back to Home',
    
    // Product Listing
    'listing.title': 'List Your Sports Equipment',
    'listing.subtitle': 'Turn your unused gear into cash',
    'listing.back': 'Back',
    'listing.continue': 'Continue',
    'listing.category': 'Category',
    'listing.category.subtitle': 'What type of sports equipment are you selling?',
    'listing.details': 'Product Details',
    'listing.details.subtitle': 'Tell us about your item',
    'listing.condition': 'Condition & Pricing',
    'listing.condition.subtitle': 'Set the condition and price',
    'listing.location': 'Location & Shipping',
    'listing.location.subtitle': 'Where is the item located?',
    'listing.photos': 'Photos',
    'listing.photos.subtitle': 'Add photos of your item',
    'listing.review': 'Review & Publish',
    'listing.review.subtitle': 'Review your listing before publishing',
    'listing.step': 'Step',
    'listing.of': 'of',
    'listing.save.draft': 'Save Draft',
    'listing.draft.saved': 'Draft saved',
    'listing.draft.saved.desc': 'Your progress has been saved.',
    'listing.error.invalid.category': 'Invalid or missing category',
    'listing.error.missing.fields': 'Missing required fields',
    'listing.success.title': 'Product listed successfully!',
    'listing.success.desc': 'Your item is now live on the marketplace.',
    'listing.error.publishing': 'Error publishing product',
    'listing.error.try.again': 'Please try again.',
    'listing.publishing': 'Publishing...',
    'listing.publish': 'Publish Product',

    // Product Listing - Category Step
    'listing.category.title': 'Product Category',
    'listing.category.desc': 'Select the sport and specific category for your item',
    'listing.category.sport': 'Sport Category',
    'listing.category.product.type': 'Product Type',
    'listing.category.size': 'Size',
    'listing.category.select.sport': 'Select sport category',
    'listing.category.select.product': 'Select product type',
    'listing.category.select.size': 'Select size',
    'listing.category.tip': 'Tip: Accurate categorization helps buyers find your item more easily!',

    // Product Listing - Details Step
    'listing.details.title': 'Product Details',
    'listing.details.desc': 'Tell us about your item',
    'listing.details.brand': 'Brand',
    'listing.details.brand.search': 'Search for brand...',
    'listing.details.brand.use': 'Use',
    'listing.details.name': 'Product Name',
    'listing.details.name.placeholder': 'e.g. Nike Air Max 90 Triple White',
    'listing.details.name.tip': 'Be specific and include key details',
    'listing.details.description': 'Description (Optional)',
    'listing.details.description.placeholder': 'Describe your item\'s condition, how you used it, why you\'re selling...',
    'listing.details.description.tip': 'Help buyers understand your item better',
    'listing.details.suggestions': 'Suggestions:',
    'listing.details.templates': 'Quick templates:',
    'listing.details.template.1': 'Great condition, barely used',
    'listing.details.template.2': 'Perfect for beginners',
    'listing.details.template.3': 'Selling due to size change',
    'listing.details.template.4': 'Excellent performance gear',
    'listing.details.tips.title': 'Listing Tips',
    'listing.details.tips.1': '• Include model names and specific details',
    'listing.details.tips.2': '• Mention the original purchase date if recent',
    'listing.details.tips.3': '• Be honest about any wear or defects',
    'listing.details.tips.4': '• Items with detailed descriptions sell faster',

    // Product Listing - Condition & Pricing Step
    'listing.condition.title': 'Condition & Price',
    'listing.condition.desc': 'Be honest about condition to build trust with buyers',
    'listing.condition.whats': 'What\'s the condition?',
    'listing.condition.new': 'New with Tags',
    'listing.condition.new.desc': 'Never worn, tags attached',
    'listing.condition.like.new': 'Like New',
    'listing.condition.like.new.desc': 'Worn once or twice, no visible wear',
    'listing.condition.good': 'Good',
    'listing.condition.good.desc': 'Some signs of wear, good condition',
    'listing.condition.fair': 'Fair',
    'listing.condition.fair.desc': 'Noticeable wear but functional',
    'listing.condition.poor': 'Poor',
    'listing.condition.poor.desc': 'Significant wear, may have defects',
    'listing.condition.set.price': 'Set your price',
    'listing.condition.original.price': 'Original Price (Optional)',
    'listing.condition.original.price.tip': 'Shows buyers how much they\'re saving',
    'listing.condition.selling.price': 'Your Selling Price',
    'listing.condition.use.suggested': 'Use suggested:',
    'listing.condition.off.original': '% off original price',
    'listing.condition.allow.offers': 'Allow offers',
    'listing.condition.allow.offers.desc': 'Let buyers make offers below your asking price',
    'listing.condition.pricing.tips': 'Pricing Tips',
    'listing.condition.tips.1': '• Items priced competitively sell 3x faster',
    'listing.condition.tips.2': '• Check similar listings for price guidance',
    'listing.condition.tips.3': '• Consider condition when pricing',
    'listing.condition.tips.4': '• Round numbers (£20, £50) often work better',
    'listing.condition.tips.5': '• You can always adjust the price later',

    // Product Listing - Location & Shipping Step
    'listing.location.title': 'Location & Delivery',
    'listing.location.desc': 'Let buyers know where you\'re located and how they can get the item',
    'listing.location.your.location': 'Your Location',
    'listing.location.placeholder': 'Enter your city or postal code',
    'listing.location.current': 'Use Current Location',
    'listing.location.tip': 'This helps calculate shipping costs and shows local buyers',
    'listing.location.how.buyers': 'How can buyers get this item?',
    'listing.location.select.all': 'Select all options you\'re comfortable with',
    'listing.location.standard': 'Standard Delivery',
    'listing.location.standard.desc': '3-5 business days',
    'listing.location.express': 'Express Delivery',
    'listing.location.express.desc': '1-2 business days',
    'listing.location.collection': 'Collection Only',
    'listing.location.collection.desc': 'Buyer collects from you',
    'listing.location.meet': 'Meet in Person',
    'listing.location.meet.desc': 'Meet locally for handover',
    'listing.location.free': 'Free',
    'listing.location.delivery.tips': 'Delivery Tips',
    'listing.location.tips.1': '• Offering multiple options increases your chances of sale',
    'listing.location.tips.2': '• Collection/meet-up saves on shipping costs',
    'listing.location.tips.3': '• Package items securely for shipping',
    'listing.location.tips.4': '• Consider insurance for valuable items',
    'listing.location.tips.5': '• Communicate clearly with buyers about handover',
    'listing.location.meeting.safely': 'Meeting Safely',
    'listing.location.safety.1': '• Meet in public places (shopping centers, cafes)',
    'listing.location.safety.2': '• Bring a friend if possible',
    'listing.location.safety.3': '• Meet during daylight hours',
    'listing.location.safety.4': '• Let someone know where you\'re going',
    'listing.location.safety.5': '• Trust your instincts',

    // Product Listing - Photo Upload Step
    'listing.photos.title': 'Add Photos',
    'listing.photos.desc': 'Add up to 8 photos. Use good lighting and clean backgrounds for best results.',
    'listing.photos.count': 'images',
    'listing.photos.take': 'Take Photo',
    'listing.photos.take.desc': 'Use your camera',
    'listing.photos.upload': 'Upload Photos',
    'listing.photos.upload.desc': 'From your gallery',
    'listing.photos.rejected': 'Some files rejected',
    'listing.photos.rejected.desc': 'Please use JPEG, PNG, or WebP files under 5MB.',
    'listing.photos.limit': 'Image limit reached',
    'listing.photos.limit.desc': 'images added. Maximum 8 images allowed.',
    'listing.photos.main': 'Main',
    'listing.photos.tips.title': 'Photo Tips',
    'listing.photos.tips.1': '• Use natural lighting when possible',
    'listing.photos.tips.2': '• Take photos from multiple angles',
    'listing.photos.tips.3': '• Show any wear or defects clearly',
    'listing.photos.tips.4': '• Include size tags or labels if visible',
    'listing.photos.tips.5': '• First photo will be the main listing image',
    'listing.photos.tips.6': '• Maximum 8 photos, 5MB each',
    'listing.photos.tips.7': '• Supported formats: JPEG, PNG, WebP',

    // Product Listing - Review & Publish Step
    'listing.review.title': 'Review & Publish',
    'listing.review.desc': 'Check everything looks good before going live',
    'listing.review.quality.score': 'Listing Quality Score',
    'listing.review.estimated.views': 'views in first week',
    'listing.review.improve': 'Add more photos and details to improve visibility',
    'listing.review.mobile.preview': 'Mobile Preview',
    'listing.review.desktop.preview': 'Desktop Preview',
    'listing.review.no.image': 'No image',
    'listing.review.product.name': 'Product name',
    'listing.review.location': 'Location',
    'listing.review.condition': 'Condition',
    'listing.review.summary': 'Listing Summary',
    'listing.review.product': 'Product:',
    'listing.review.brand': 'Brand:',
    'listing.review.category': 'Category:',
    'listing.review.size': 'Size:',
    'listing.review.price': 'Price:',
    'listing.review.delivery': 'Delivery:',
    'listing.review.options.available': 'options available',
    'listing.review.ready': 'Ready to go live?',
    'listing.review.visible': 'Your listing will be visible to thousands of sports enthusiasts',
    'listing.review.publish.button': '🚀 Publish My Listing',
    'listing.review.edit.anytime': 'You can edit or remove your listing anytime from your seller dashboard',

    // Features
    'features.title': 'Why Choose Resportz?',
    'features.subtitle': 'The smarter way to buy and sell sports equipment',
    'features.quality.title': 'Quality Guaranteed',
    'features.quality.desc': 'Every piece of equipment is verified by our community of sports enthusiasts',
    'features.sustainable.title': 'Sustainable Sports',
    'features.sustainable.desc': 'Give sports equipment a second life while saving money and the environment',
    'features.community.title': 'Community Driven',
    'features.community.desc': 'Connect with fellow athletes and sports enthusiasts in your area',
    'features.secure.title': 'Secure Transactions',
    'features.secure.desc': 'Safe and secure payments with buyer and seller protection',
    
    // Testimonials
    'testimonials.title': 'What Our Community Says',
    'testimonials.subtitle': 'Join thousands of satisfied athletes who trust Resportz',
    'testimonials.role.runner': 'Marathon Runner',
    'testimonials.role.golf': 'Golf Enthusiast', 
    'testimonials.role.coach': 'Football Coach',
    'testimonials.role.trail': 'Trail Runner',
    'testimonials.michael.text': 'I\'ve saved over $500 on running shoes alone this year using recliq.eu. The quality is amazing and I love that I\'m helping reduce waste.',
    'testimonials.sarah.text': 'Found a nearly new set of clubs for my daughter at half the retail price. The seller was fantastic and shipping was fast!',
    'testimonials.david.text': 'As a coach for a youth team, recliq.eu has been invaluable. I\'m able to get quality equipment for my players at prices parents can afford.',
    'testimonials.jessica.text': 'Sold my old trail shoes after upgrading and bought a hydration pack with the money. recliq.eu makes the circular economy of sports gear possible!',
    
    // Footer
    'footer.about': 'About Resportz',
    'footer.about.desc': 'The sustainable marketplace connecting athletes with quality pre-owned sports equipment.',
    'footer.quick.links': 'Quick Links',
    'footer.categories': 'Categories',
    'footer.support': 'Support',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.size': 'Size',
    'common.condition': 'Condition',
    'common.brand': 'Brand',
    'common.price': 'Price',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.share': 'Share',
    'common.like': 'Like',
    'common.favorite': 'Favorite',
    
    // Profile translations
    'profile.signin.required': 'Please sign in to view your profile',
    'profile.statistics.title': 'Your Statistics',
    'profile.statistics.total.listings': 'Total Listings',
    'profile.statistics.active.listings': 'Active Listings',
    'profile.statistics.items.sold': 'Items Sold',
    'profile.statistics.total.views': 'Total Views',
    'profile.statistics.total.earnings': 'Total Earnings',
    'profile.statistics.response.rate': 'Response Rate',
    'profile.statistics.avg.rating': 'Avg Rating',
    'profile.statistics.no.ratings': 'No ratings yet',
    'profile.member.since': 'Member since',
    'profile.ready.selling': 'Ready to start selling?',
    'profile.first.listing.desc': 'List your first item and start earning from your unused sports equipment!',
    'profile.create.first.listing': 'Create Your First Listing',
    'profile.listings': 'Listings',
    
    // Dashboard translations
    'dashboard.signin.required': 'Please sign in to access your dashboard',
    'dashboard.buyer.title': 'Buyer Dashboard',
    'dashboard.welcome.back': 'Welcome back',
    'dashboard.buyer': 'Buyer',
    'dashboard.discover.deals': 'Discover great sports equipment deals.',
    'dashboard.total.orders': 'Total Orders',
    'dashboard.total.spent': 'Total Spent',
    'dashboard.cart.items': 'Cart Items',
    'dashboard.sports.interests': 'Sports Interests',
    'dashboard.discover.equipment': 'Discover new sports equipment',
    'dashboard.view.cart': 'View Cart',
    'dashboard.items.in.cart': 'items in your cart',
    'dashboard.update.preferences': 'Update your preferences',
    'dashboard.your.sports.interests': 'Your Sports Interests',
    'dashboard.recent.orders': 'Recent Orders',
    'dashboard.no.orders': 'No orders yet',
    'dashboard.start.shopping.desc': 'Start shopping to see your orders here',
    'dashboard.seller': 'Seller',
    'dashboard.view.all.orders': 'View All Orders',
  },
  nl: {
    // Navigation
    'nav.browse': 'Bladeren',
    'nav.golf': 'Golf',
    'nav.tennis': 'Tennis',
    'nav.padel': 'Padel',
    'nav.hockey': 'Hockey',
    'nav.cycling': 'Wielrennen',
    'nav.signin': 'Inloggen',
    'nav.profile': 'Profiel',
    'nav.orders': 'Mijn Bestellingen',
    'nav.list': 'Item Verkopen',
    'nav.signout': 'Uitloggen',
    
    // Auth
    'auth.welcome': 'Welkom Terug',
    'auth.subtitle': 'Log in om je duurzame sportreis voort te zetten',
    'auth.tagline': 'HERBELEVEN. HERLIEFHEBBEN. RESPORTZ.',
    'auth.email': 'E-mail',
    'auth.password': 'Wachtwoord',
    'auth.signin': 'Inloggen',
    'auth.signing': 'Inloggen...',
    'auth.noaccount': 'Geen account? Word lid van Resportz',
    'auth.back': 'Terug naar Home',
    'auth.enter.email': 'Voer je e-mail in',
    'auth.enter.password': 'Voer je wachtwoord in',
    
    // Hero Section
    'hero.title': 'Resportz',
    'hero.tagline': 'HERBELEVEN. HERLIEFHEBBEN. RESPORTZ.',
    'hero.subtitle': 'De duurzame marktplaats voor sportuitrusting. Koop en verkoop kwaliteitsuitrusting van gepassioneerde atleten in je gemeenschap.',
    'hero.cta': 'Begin Nu',
    'hero.browse': 'Blader door Producten',
    'hero.verified': 'Geverifieerde Kwaliteit',
    'hero.secure': 'Veilige Betalingen',
    'hero.local': 'Lokale Gemeenschap',
    'hero.quote': 'Vind premium sportuitrusting van mede-atleten die kwaliteitsuitrusting kennen',
    'hero.quote.author': 'De Resportz Gemeenschap',
    
    // Home/Landing
    'hero.cta.alt': 'Begin met Winkelen',
    'hero.list': 'Verkoop je Uitrusting',
    'home.welcome': 'Welkom bij Resportz!',
    'home.welcome.user': 'Welkom',
    'home.subtitle': 'Je duurzame sportmarktplaats is klaar. Kies hoe je wilt beginnen.',
    'home.start.shopping': 'Begin met Winkelen',
    'home.start.shopping.desc': 'Blader door kwaliteit tweedehands sportuitrusting van mede-atleten. Vind uitrusting die presteert tegen geweldige prijzen.',
    'home.start.selling': 'Begin met Verkopen',
    'home.start.selling.desc': 'Geef je sportuitrusting een tweede leven. Verdien geld terwijl je andere atleten helpt.',
    'home.list.gear': 'Verkoop je Uitrusting',
    'home.browse.products': 'Blader door Producten',
    'home.stats.athletes': 'Actieve Atleten',
    'home.stats.sold': 'Verkochte Items',
    'home.stats.satisfaction': 'Tevredenheidscore',
    'home.popular.categories': 'Populaire Categorieën',
    'home.popular.desc': 'Ontdek kwaliteitsuitrusting voor al je favoriete sporten',
    'home.cta.title': 'Klaar om mee te doen?',
    'home.cta.subtitle': 'Duurzame sportuitrustinghandel voor atleten, door atleten',
    'home.why.title': 'Waarom Resportz Kiezen?',
    'home.why.subtitle': 'De slimme, efficiënte manier om kwaliteit sportuitrusting te kopen en verkopen. Wij maken het verhandelen van sportuitrusting eenvoudig, veilig en gemeenschapsgericht.',
    'home.effortless.title': 'Moeiteloze Handel',
    'home.effortless.desc': 'Verkoop je uitrusting in minuten of vind precies wat je nodig hebt met ons gestroomlijnde platform ontworpen voor drukke atleten.',
    'home.quality.title': 'Kwaliteit Gegarandeerd',
    'home.quality.desc': 'Elk item wordt zorgvuldig gecontroleerd door onze gemeenschap van sportliefhebbers om ervoor te zorgen dat je uitrusting krijgt die presteert.',
    'home.community.title': 'Gemeenschapsgedreven',
    'home.community.desc': 'Verbind met mede-atleten en sportliefhebbers in jouw gebied',
    'home.secure.title': 'Veilige Transacties',
    'home.secure.desc': 'Veilige betalingen met koper- en verkopersbescherming',
    
    // Browse
    'browse.title': 'Producten Bladeren',
    'browse.subtitle': 'Ontdek kwaliteit tweedehands sportuitrusting van vertrouwde verkopers',
    'browse.search': 'Zoek producten, merken...',
    'browse.all': 'Alle Producten',
    'browse.items': 'items',
    'browse.continue': 'Verder Winkelen',
    'browse.error': 'Fout bij laden producten',
    
    // Categories
    'category.golf': 'Golf',
    'category.golf.desc': 'Professionele clubs, ballen en accessoires voor elke golfer',
    'category.golf.detailed': 'Clubs, ballen, kleding en golf accessoires',
    'category.tennis': 'Tennis',
    'category.tennis.desc': 'Rackets, schoenen en uitrusting voor kampioenen op de baan',
    'category.tennis.detailed': 'Rackets, balls, shoes, apparel, en baan accessoires',
    'category.padel': 'Padel',
    'category.padel.desc': 'Rackets en uitrusting voor de snelst groeiende sport',
    'category.padel.detailed': 'Rackets, balls, shoes, apparel, en baan uitrusting',
    'category.hockey': 'Hockey',
    'category.hockey.desc': 'Sticks, schaatsen en beschermende uitrusting voor ijsguerrillers',
    'category.hockey.detailed': 'Sticks, pucks, beschermende uitrusting en hockey accessoires',
    'category.cycling': 'Wielrennen',
    'category.cycling.desc': 'Fietsen, helmen en accessoires voor elke rit',
    'category.cycling.detailed': 'Fietsen, onderdelen, kleding en fiets accessoires',
    'category.equipment': 'Uitrusting',
    'category.browse': 'Blader door',
    'category.from': 'uitrusting van vertrouwde verkopers',
    'category.shop.title': 'Winkel op Sport',
    'category.shop.subtitle': 'Ontdek kwaliteit sportuitrusting voor al je favoriete sporten',
    'category.browse.all.sports': 'Blader door Alle Sporten',
    
    // Product
    'product.condition': 'Conditie',
    'product.size': 'Maat',
    'product.description': 'Beschrijving',
    'product.add.cart': 'Toevoegen aan Winkelwagen',
    'product.contact.seller': 'Verkoper Direct Contacteren',
    'product.not.available': 'Niet Beschikbaar',
    'product.own.product': 'Dit is jouw product',
    'product.save.amount': 'Je bespaart',
    'product.seller': 'Door',
    'product.loading': 'Laden...',
    'product.error': 'Product niet gevonden',
    'product.related': 'Gerelateerde Producten',
    'product.shipping': 'Verzending & Retouren',
    'product.shipping.desc': 'Gratis verzending bij bestellingen boven €50. 30 dagen retourbeleid.',
    
    // Featured Products
    'featured.title': 'Uitgelichte Producten',
    'featured.view.all': 'Bekijk Alles',
    
    // Cart
    'cart.title': 'Winkelwagen',
    'cart.signin': 'Log in om je winkelwagen te bekijken',
    'cart.empty': 'Je winkelwagen is leeg',
    'cart.empty.subtitle': 'Het lijkt erop dat je nog geen items aan je winkelwagen hebt toegevoegd',
    'cart.start': 'Begin met Winkelen',
    'cart.subtotal': 'Subtotaal',
    'cart.shipping': 'Verzending',
    'cart.free': 'Gratis',
    'cart.total': 'Totaal',
    'cart.checkout': 'Ga naar Afrekenen',
    'cart.quantity': 'Aantal',
    
    // Checkout
    'checkout.title': 'Afrekenen',
    'checkout.signin': 'Log in om af te rekenen',
    'checkout.shipping': 'Verzendadres',
    'checkout.payment': 'Betaalmethode',
    'checkout.summary': 'Bestelling Overzicht',
    'checkout.fullname': 'Volledige Naam',
    'checkout.address': 'Adres',
    'checkout.city': 'Stad',
    'checkout.postal': 'Postcode',
    'checkout.country': 'Land',
    'checkout.subtotal': 'Subtotaal',
    'checkout.commission': 'ReSport commissie (5%)',
    'checkout.pay': 'Betaal met Stripe',
    'checkout.creating': 'Afrekenen aanmaken...',
    'checkout.held': 'Betaling vastgehouden tot bezorgverificatie. Verkopers ontvangen 95% na voltooiing.',
    'checkout.secure': 'Veilige betalingsverwerking via Stripe. Betaling wordt vastgehouden tot bezorgverificatie voltooid is.',
    
    // Success/Cancel
    'success.title': 'Betaling Succesvol!',
    'success.thanks': 'Dank je voor je aankoop! Je betaling is ontvangen en wordt veilig vastgehouden tot bezorgverificatie.',
    'success.reference': 'Bestelling Referentie',
    'success.details': '• Betaling wordt veilig vastgehouden tot bezorgverificatie\n• Verkopers worden op de hoogte gebracht van je bestelling\n• Je ontvangt tracking informatie zodra verzonden\n• Verkopers ontvangen betaling na succesvolle bezorging',
    'success.orders': 'Bekijk Bestellingen',
    'success.continue': 'Verder Winkelen',
    'success.processing': 'Je bestelling verwerken...',
    
    'cancel.title': 'Betaling Geannuleerd',
    'cancel.message': 'Je betaling is geannuleerd. Er zijn geen kosten in rekening gebracht.',
    'cancel.cart': 'Je items staan nog steeds in je winkelwagen en je kunt je aankoop voltooien wanneer je klaar bent.',
    'cancel.return': 'Terug naar Winkelwagen',

    // Signup
    'signup.title': 'Maak je Account',
    'signup.subtitle': 'Word lid van de duurzame sportgemeenschap',
    'signup.fullname': 'Volledige Naam',
    'signup.fullname.placeholder': 'Voer je volledige naam in',
    'signup.password.placeholder': 'Maak een wachtwoord',
    'signup.create': 'Account Aanmaken',
    'signup.creating': 'Account Aanmaken...',
    'signup.hasaccount': 'Al een account? Inloggen',
    'signup.name.required': 'Naam vereist',
    'signup.name.required.desc': 'Voer je volledige naam in.',
    'signup.email.required': 'E-mail vereist',
    'signup.email.required.desc': 'Voer je e-mailadres in.',
    'signup.password.required': 'Wachtwoord vereist',
    'signup.password.required.desc': 'Voer een wachtwoord in.',
    'signup.account.exists': 'Account bestaat',
    'signup.account.exists.desc': 'Er bestaat al een account met dit e-mailadres. Probeer in te loggen.',
    'signup.failed': 'Registratie mislukt',
    'signup.success': 'Account aangemaakt!',
    'signup.success.desc': 'Welkom bij ReSport! Laten we je profiel voltooien.',
    'signup.error.general': 'Er ging iets mis. Probeer het opnieuw.',

    // Onboarding
    'onboarding.subtitle': 'Word lid van de duurzame sportbeweging. Koop en verkoop kwaliteit tweedehands sportuitrusting voor hardlopen, golf, voetbal en meer.',
    'onboarding.buyer': 'Ik ben een Koper',
    'onboarding.buyer.desc': 'Ontdek kwaliteit tweedehands sportuitrusting tegen geweldige prijzen. Van hardloopschoenen tot golfclubs, vind uitrusting die presteert.',
    'onboarding.seller': 'Ik ben een Verkoper',
    'onboarding.seller.desc': 'Geef je sportuitrusting een tweede leven. Verdien geld terwijl je andere atleten helpt kwaliteitsuitrusting te vinden.',
    'onboarding.start.shopping': 'Begin met Winkelen',
    'onboarding.signup.buy': 'Registreer om te Kopen',
    'onboarding.start.selling': 'Begin met Verkopen',
    'onboarding.signup.sell': 'Registreer om te Verkopen',
    'onboarding.community': 'Gemeenschap',
    'onboarding.community.desc': 'Verbind met mede-atleten',
    'onboarding.quality': 'Kwaliteit',
    'onboarding.quality.desc': 'Geverifieerde uitrusting die je kunt vertrouwen',
    'onboarding.sustainable': 'Duurzaam',
    'onboarding.sustainable.desc': 'Beter voor jou en de planeet',

    // Not Found
    'notfound.title': 'Pagina Niet Gevonden',
    'notfound.message': 'Sorry, we konden de pagina die je zoekt niet vinden. Misschien heb je de URL verkeerd getypt of is de pagina verplaatst.',
    'notfound.home': 'Terug naar Home',
    
    // Product Listing
    'listing.title': 'Verkoop je Sportuitrusting',
    'listing.subtitle': 'Verdien geld met je ongebruikte uitrusting',
    'listing.back': 'Terug',
    'listing.continue': 'Doorgaan',
    'listing.category': 'Categorie',
    'listing.category.subtitle': 'Wat voor type sportuitrusting verkoop je?',
    'listing.details': 'Product Details',
    'listing.details.subtitle': 'Vertel ons over je item',
    'listing.condition': 'Conditie & Prijsstelling',
    'listing.condition.subtitle': 'Stel de conditie en prijs in',
    'listing.location': 'Locatie & Bezorging',
    'listing.location.subtitle': 'Waar bevindt het item zich?',
    'listing.photos': 'Foto\'s',
    'listing.photos.subtitle': 'Voeg foto\'s van je item toe',
    'listing.review': 'Controleren & Publiceren',
    'listing.review.subtitle': 'Controleer je advertentie voordat je publiceert',
    'listing.step': 'Stap',
    'listing.of': 'van',
    'listing.save.draft': 'Concept Opslaan',
    'listing.draft.saved': 'Concept opgeslagen',
    'listing.draft.saved.desc': 'Je voortgang is opgeslagen.',
    'listing.error.invalid.category': 'Ongeldige of ontbrekende categorie',
    'listing.error.missing.fields': 'Vereiste velden ontbreken',
    'listing.success.title': 'Product succesvol verkocht!',
    'listing.success.desc': 'Je item is nu live op de marktplaats.',
    'listing.error.publishing': 'Fout bij publiceren product',
    'listing.error.try.again': 'Probeer het opnieuw.',
    'listing.publishing': 'Publiceren...',
    'listing.publish': 'Product Publiceren',

    // Product Listing - Category Step
    'listing.category.title': 'Productcategorie',
    'listing.category.desc': 'Selecteer de sport en specifieke categorie voor je item',
    'listing.category.sport': 'Sportcategorie',
    'listing.category.product.type': 'Producttype',
    'listing.category.size': 'Maat',
    'listing.category.select.sport': 'Selecteer sportcategorie',
    'listing.category.select.product': 'Selecteer producttype',
    'listing.category.select.size': 'Selecteer maat',
    'listing.category.tip': 'Tip: Nauwkeurige categorisatie helpt kopers je item gemakkelijker te vinden!',

    // Product Listing - Details Step
    'listing.details.title': 'Productdetails',
    'listing.details.desc': 'Vertel ons over je item',
    'listing.details.brand': 'Merk',
    'listing.details.brand.search': 'Zoek naar merk...',
    'listing.details.brand.use': 'Gebruik',
    'listing.details.name': 'Productnaam',
    'listing.details.name.placeholder': 'bijv. Nike Air Max 90 Triple White',
    'listing.details.name.tip': 'Wees specifiek en voeg belangrijke details toe',
    'listing.details.description': 'Beschrijving (Optioneel)',
    'listing.details.description.placeholder': 'Beschrijf de conditie van je item, hoe je het hebt gebruikt, waarom je het verkoopt...',
    'listing.details.description.tip': 'Help kopers je item beter te begrijpen',
    'listing.details.suggestions': 'Suggesties:',
    'listing.details.templates': 'Snelle sjablonen:',
    'listing.details.template.1': 'Geweldige conditie, nauwelijks gebruikt',
    'listing.details.template.2': 'Perfect voor beginners',
    'listing.details.template.3': 'Verkoop vanwege maatwijziging',
    'listing.details.template.4': 'Uitstekende prestatie-uitrusting',
    'listing.details.tips.title': 'Advertentie Tips',
    'listing.details.tips.1': '• Voeg modelnamen en specifieke details toe',
    'listing.details.tips.2': '• Vermeld de oorspronkelijke aankoopdatum indien recent',
    'listing.details.tips.3': '• Wees eerlijk over slijtage of defecten',
    'listing.details.tips.4': '• Items met gedetailleerde beschrijvingen verkopen sneller',

    // Product Listing - Condition & Pricing Step
    'listing.condition.title': 'Conditie & Prijs',
    'listing.condition.desc': 'Wees eerlijk over de conditie om vertrouwen op te bouwen bij kopers',
    'listing.condition.whats': 'Wat is de conditie?',
    'listing.condition.new': 'Nieuw met Labels',
    'listing.condition.new.desc': 'Nooit gedragen, labels nog bevestigd',
    'listing.condition.like.new': 'Als Nieuw',
    'listing.condition.like.new.desc': 'Een of twee keer gedragen, geen zichtbare slijtage',
    'listing.condition.good': 'Goed',
    'listing.condition.good.desc': 'Enkele tekenen van slijtage, goede conditie',
    'listing.condition.fair': 'Redelijk',
    'listing.condition.fair.desc': 'Merkbare slijtage maar functioneel',
    'listing.condition.poor': 'Slecht',
    'listing.condition.poor.desc': 'Aanzienlijke slijtage, kan defecten hebben',
    'listing.condition.set.price': 'Stel je prijs in',
    'listing.condition.original.price': 'Oorspronkelijke Prijs (Optioneel)',
    'listing.condition.original.price.tip': 'Toont kopers hoeveel ze besparen',
    'listing.condition.selling.price': 'Jouw Verkoopprijs',
    'listing.condition.use.suggested': 'Gebruik voorgesteld:',
    'listing.condition.off.original': '% korting op oorspronkelijke prijs',
    'listing.condition.allow.offers': 'Biedingen toestaan',
    'listing.condition.allow.offers.desc': 'Laat kopers biedingen doen onder je vraagprijs',
    'listing.condition.pricing.tips': 'Prijsstellingstips',
    'listing.condition.tips.1': '• Competitief geprijsde items verkopen 3x sneller',
    'listing.condition.tips.2': '• Controleer vergelijkbare advertenties voor prijsrichtlijnen',
    'listing.condition.tips.3': '• Overweeg conditie bij prijsstelling',
    'listing.condition.tips.4': '• Ronde nummers (€20, €50) werken vaak beter',
    'listing.condition.tips.5': '• Je kunt de prijs altijd later aanpassen',

    // Product Listing - Location & Shipping Step
    'listing.location.title': 'Locatie & Bezorging',
    'listing.location.desc': 'Laat kopers weten waar je bent en hoe ze het item kunnen krijgen',
    'listing.location.your.location': 'Jouw Locatie',
    'listing.location.placeholder': 'Voer je stad of postcode in',
    'listing.location.current': 'Gebruik Huidige Locatie',
    'listing.location.tip': 'Dit helpt bij het berekenen van verzendkosten en toont lokale kopers',
    'listing.location.how.buyers': 'Hoe kunnen kopers dit item krijgen?',
    'listing.location.select.all': 'Selecteer alle opties waar je je comfortabel bij voelt',
    'listing.location.standard': 'Standaard Bezorging',
    'listing.location.standard.desc': '3-5 werkdagen',
    'listing.location.express': 'Express Bezorging',
    'listing.location.express.desc': '1-2 werkdagen',
    'listing.location.collection': 'Alleen Ophalen',
    'listing.location.collection.desc': 'Koper haalt op bij jou',
    'listing.location.meet': 'Persoonlijk Ontmoeten',
    'listing.location.meet.desc': 'Lokaal ontmoeten voor overdracht',
    'listing.location.free': 'Gratis',
    'listing.location.delivery.tips': 'Bezorgtips',
    'listing.location.tips.1': '• Meerdere opties aanbieden verhoogt je verkanstkans',
    'listing.location.tips.2': '• Ophalen/ontmoeten bespaart verzendkosten',
    'listing.location.tips.3': '• Verpak items veilig voor verzending',
    'listing.location.tips.4': '• Overweeg verzekering voor waardevolle items',
    'listing.location.tips.5': '• Communiceer duidelijk met kopers over overdracht',
    'listing.location.meeting.safely': 'Veilig Ontmoeten',
    'listing.location.safety.1': '• Ontmoet op openbare plaatsen (winkelcentra, cafés)',
    'listing.location.safety.2': '• Neem indien mogelijk een vriend mee',
    'listing.location.safety.3': '• Ontmoet tijdens daglicht',
    'listing.location.safety.4': '• Laat iemand weten waar je naartoe gaat',
    'listing.location.safety.5': '• Vertrouw op je instinct',

    // Product Listing - Photo Upload Step
    'listing.photos.title': 'Voeg Foto\'s Toe',
    'listing.photos.desc': 'Voeg tot 8 foto\'s toe. Gebruik goede verlichting en schone achtergronden voor de beste resultaten.',
    'listing.photos.count': 'afbeeldingen',
    'listing.photos.take': 'Foto Maken',
    'listing.photos.take.desc': 'Gebruik je camera',
    'listing.photos.upload': 'Foto\'s Uploaden',
    'listing.photos.upload.desc': 'Uit je galerij',
    'listing.photos.rejected': 'Enkele bestanden geweigerd',
    'listing.photos.rejected.desc': 'Gebruik JPEG, PNG of WebP bestanden onder 5MB.',
    'listing.photos.limit': 'Afbeeldingslimiet bereikt',
    'listing.photos.limit.desc': 'afbeeldingen toegevoegd. Maximaal 8 afbeeldingen toegestaan.',
    'listing.photos.main': 'Hoofd',
    'listing.photos.tips.title': 'Fototips',
    'listing.photos.tips.1': '• Gebruik indien mogelijk natuurlijk licht',
    'listing.photos.tips.2': '• Maak foto\'s vanuit meerdere hoeken',
    'listing.photos.tips.3': '• Toon slijtage of defecten duidelijk',
    'listing.photos.tips.4': '• Voeg maatlabels toe indien zichtbaar',
    'listing.photos.tips.5': '• Eerste foto wordt de hoofdafbeelding',
    'listing.photos.tips.6': '• Maximaal 8 foto\'s, 5MB elk',
    'listing.photos.tips.7': '• Ondersteunde formaten: JPEG, PNG, WebP',

    // Product Listing - Review & Publish Step
    'listing.review.title': 'Controleren & Publiceren',
    'listing.review.desc': 'Controleer of alles er goed uitziet voordat je live gaat',
    'listing.review.quality.score': 'Advertentie Kwaliteitsscore',
    'listing.review.estimated.views': 'weergaven in eerste week',
    'listing.review.improve': 'Voeg meer foto\'s en details toe om zichtbaarheid te verbeteren',
    'listing.review.mobile.preview': 'Mobiele Voorvertoning',
    'listing.review.desktop.preview': 'Desktop Voorvertoning',
    'listing.review.no.image': 'Geen afbeelding',
    'listing.review.product.name': 'Productnaam',
    'listing.review.location': 'Locatie',
    'listing.review.condition': 'Conditie',
    'listing.review.summary': 'Advertentie Samenvatting',
    'listing.review.product': 'Product:',
    'listing.review.brand': 'Merk:',
    'listing.review.category': 'Categorie:',
    'listing.review.size': 'Maat:',
    'listing.review.price': 'Prijs:',
    'listing.review.delivery': 'Bezorging:',
    'listing.review.options.available': 'opties beschikbaar',
    'listing.review.ready': 'Klaar om live te gaan?',
    'listing.review.visible': 'Je advertentie wordt zichtbaar voor duizenden sportliefhebbers',
    'listing.review.publish.button': '🚀 Publiceer Mijn Advertentie',
    'listing.review.edit.anytime': 'Je kunt je advertentie altijd bewerken of verwijderen vanuit je verkopersdashboard',

    // Features
    'features.title': 'Waarom Resportz Kiezen?',
    'features.subtitle': 'De slimmere manier om sportuitrusting te kopen en verkopen',
    'features.quality.title': 'Kwaliteit Gegarandeerd',
    'features.quality.desc': 'Elke uitrusting wordt geverifieerd door onze gemeenschap van sportliefhebbers',
    'features.sustainable.title': 'Duurzame Sport',
    'features.sustainable.desc': 'Geef sportuitrusting een tweede leven terwijl je geld en het milieu bespaart',
    'features.community.title': 'Gemeenschapsgedreven',
    'features.community.desc': 'Verbind met mede-atleten en sportliefhebbers in jouw gebied',
    'features.secure.title': 'Veilige Transacties',
    'features.secure.desc': 'Veilige betalingen met koper- en verkopersbescherming',
    
    // Testimonials
    'testimonials.title': 'Wat Onze Gemeenschap Zegt',
    'testimonials.subtitle': 'Sluit je aan bij duizenden tevreden atleten die Resportz vertrouwen',
    'testimonials.role.runner': 'Marathonloper',
    'testimonials.role.golf': 'Golf Liefhebber', 
    'testimonials.role.coach': 'Voetbal Coach',
    'testimonials.role.trail': 'Trailloper',
    'testimonials.michael.text': 'Ik heb dit jaar alleen al meer dan $500 bespaard op hardloopschoenen door recliq.eu te gebruiken. De kwaliteit is geweldig en ik vind het leuk dat ik help afval te verminderen.',
    'testimonials.sarah.text': 'Vond een bijna nieuwe set clubs voor mijn dochter voor de helft van de verkoopprijs. De verkoper was fantastisch en verzending was snel!',
    'testimonials.david.text': 'Als coach van een jeugdteam is recliq.eu van onschatbare waarde geweest. Ik kan kwaliteitsuitrusting voor mijn spelers krijgen tegen prijzen die ouders kunnen betalen.',
    'testimonials.jessica.text': 'Verkocht mijn oude trailschoenen na een upgrade en kocht een hydratatiepak met het geld. recliq.eu maakt de circulaire economie van sportuitrusting mogelijk!',
    
    // Footer
    'footer.about': 'Over Resportz',
    'footer.about.desc': 'De duurzame marktplaats die atleten verbindt met kwaliteit tweedehands sportuitrusting.',
    'footer.quick.links': 'Snelle Links',
    'footer.categories': 'Categorieën',
    'footer.support': 'Ondersteuning',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact Ons',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Servicevoorwaarden',
    'footer.rights': 'Alle rechten voorbehouden.',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fout',
    'common.size': 'Maat',
    'common.condition': 'Conditie',
    'common.brand': 'Merk',
    'common.price': 'Prijs',
    'common.name': 'Naam',
    'common.description': 'Beschrijving',
    'common.save': 'Opslaan',
    'common.cancel': 'Annuleren',
    'common.edit': 'Bewerken',
    'common.delete': 'Verwijderen',
    'common.add': 'Toevoegen',
    'common.remove': 'Verwijderen',
    'common.back': 'Terug',
    'common.next': 'Volgende',
    'common.previous': 'Vorige',
    'common.submit': 'Indienen',
    'common.search': 'Zoeken',
    'common.filter': 'Filteren',
    'common.sort': 'Sorteren',
    'common.view': 'Bekijken',
    'common.share': 'Delen',
    'common.like': 'Leuk vinden',
    'common.favorite': 'Favoriet',
    
    // Profile translations
    'profile.signin.required': 'Log in om je profiel te bekijken',
    'profile.statistics.title': 'Jouw Statistieken',
    'profile.statistics.total.listings': 'Totaal Advertenties',
    'profile.statistics.active.listings': 'Actieve Advertenties',
    'profile.statistics.items.sold': 'Verkochte Items',
    'profile.statistics.total.views': 'Totaal Weergaven',
    'profile.statistics.total.earnings': 'Totale Inkomsten',
    'profile.statistics.response.rate': 'Reactiesnelheid',
    'profile.statistics.avg.rating': 'Gem. Beoordeling',
    'profile.statistics.no.ratings': 'Nog geen beoordelingen',
    'profile.member.since': 'Lid sinds',
    'profile.ready.selling': 'Klaar om te beginnen met verkopen?',
    'profile.first.listing.desc': 'Verkoop je eerste item en begin geld te verdienen met je ongebruikte sportuitrusting!',
    'profile.create.first.listing': 'Maak Je Eerste Advertentie',
    'profile.listings': 'Advertenties',
    
    // Dashboard translations
    'dashboard.signin.required': 'Log in om toegang te krijgen tot je dashboard',
    'dashboard.buyer.title': 'Koper Dashboard',
    'dashboard.welcome.back': 'Welkom terug',
    'dashboard.buyer': 'Koper',
    'dashboard.discover.deals': 'Ontdek geweldige sportuitrusting aanbiedingen.',
    'dashboard.total.orders': 'Totaal Bestellingen',
    'dashboard.total.spent': 'Totaal Uitgegeven',
    'dashboard.cart.items': 'Winkelwagen Items',
    'dashboard.sports.interests': 'Sport Interesses',
    'dashboard.discover.equipment': 'Ontdek nieuwe sportuitrusting',
    'dashboard.view.cart': 'Bekijk Winkelwagen',
    'dashboard.items.in.cart': 'items in je winkelwagen',
    'dashboard.update.preferences': 'Update je voorkeuren',
    'dashboard.your.sports.interests': 'Jouw Sport Interesses',
    'dashboard.recent.orders': 'Recente Bestellingen',
    'dashboard.no.orders': 'Nog geen bestellingen',
    'dashboard.start.shopping.desc': 'Begin met winkelen om je bestellingen hier te zien',
    'dashboard.seller': 'Verkoper',
    'dashboard.view.all.orders': 'Bekijk Alle Bestellingen',
  }
};

// LanguageProvider component and useLanguage hook
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [loading, setLoading] = useState(false);
  const { user, profile } = useAuth();

  // Load language preference from user profile or localStorage
  useEffect(() => {
    const loadLanguagePreference = async () => {
      if (user && profile) {
        // Use language from user profile if available
        const userLanguage = profile.language as Language;
        if (userLanguage && (userLanguage === 'en' || userLanguage === 'nl')) {
          setLanguageState(userLanguage);
          // Also sync to localStorage for immediate access
          localStorage.setItem('resportz-language', userLanguage);
          return;
        }
      }

      // Fall back to localStorage if user not logged in or no profile language set
      const savedLanguage = localStorage.getItem('resportz-language') as Language;
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'nl')) {
        setLanguageState(savedLanguage);
      }
    };

    loadLanguagePreference();
  }, [user, profile]);

  const setLanguage = async (lang: Language) => {
    setLoading(true);
    try {
      // Update local state immediately for responsive UI
      setLanguageState(lang);
      
      // Always update localStorage
      localStorage.setItem('resportz-language', lang);

      // Update Supabase profile if user is logged in
      if (user) {
        const { error } = await supabase
          .from('profiles')
          .update({ language: lang })
          .eq('id', user.id);

        if (error) {
          console.error('Error updating language preference:', error);
          // Don't revert the UI change, just log the error
        } else {
          console.log('Language preference updated in Supabase:', lang);
        }
      }
    } catch (error) {
      console.error('Error setting language:', error);
    } finally {
      setLoading(false);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, loading }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
